### ISSUE TITLE
Missing function return?

### ISSUE THREAD

**Issue by tkrempser** [czue/celery-progress#10]
https://github.com/czue/celery-progress/blob/bcf9aab861cd1db90f43f310ac53d8b273dcd070/celery_progress/backend.py#L76

**Comment by mcrot** [comment]
Ups, I've used a wrong commit message in https://github.com/mcrot/celery-progress/commit/825ace3ea6fd2a14cc97c1ed907873f0b756d2fc. I used "Closing" instead of "Closes". This can be closed now.

**Comment by czue** [comment]
Yep, just doing some final testing then will cut a new release to pypi and close

**Comment by czue** [comment]
fixed in `0.0.4` - thanks!
