### ISSUE TITLE
Using master branch leads to Javascript TypeError

### ISSUE THREAD

**Issue by Whitie** [czue/celery-progress#102]
The commit 17ac00d1f842cac5646933aa6dff88ed20165979 introduced a static method to retrieve the bar colors. Calling a static method from the constructor fails with a TypeError. See https://stackoverflow.com/questions/37002804/calling-static-method-from-constructor-es6 for explanation.
Line 25 of celery_progress.js must be changed from:
```
this.barColors = Object.assign({}, getBarColorsDefault(), options.barColors);
```
to:
```
this.barColors = Object.assign({}, this.constructor.getBarColorsDefault(), options.barColors);
```
It's just a little change, should I make a pull request for this?

Whitie

**Comment by czue** [comment]
Eep, sorry about that! A PR would be great!
