### ISSUE TITLE
django.conf.urls.url() deprecated in Django 3+, removed in 4.0

### ISSUE THREAD

**Issue by boxofbox** [czue/celery-progress#105]
In websockets.routing, need to change from 

```python
from django.conf.urls import url
...
urlpatterns = [
    url(r'^ws/progress/(?P<task_id>[\w-]+)/?$', progress_consumer),
]
```
to

```python
from django.urls import re_path
...
urlpatterns = [
    re_path(r'^ws/progress/(?P<task_id>[\w-]+)/?$', progress_consumer),
]
```

**Comment by boxofbox** [comment]
nevermind. looks like this is only an issue in 0.1.3 (downloaded via pip) and not the current master branch.

**Comment by czue** [comment]
Oops, good reminder to push out a new version though. Will do so after #106 is also resolved.

**Comment by czue** [comment]
https://github.com/czue/celery-progress/releases/tag/0.2
