### ISSUE TITLE
using websockets with channels_redis 4.0.0+ leads to RuntimeError("Event loop is closed")

### ISSUE THREAD

**Issue by boxofbox** [czue/celery-progress#106]
see also: https://github.com/django/channels_redis/issues/332

in websockets.backend the call to aync_to_sync needs to be wrapped in a closing function:

e.g.,
```python
async def closing_send(channel_layer, channel, message):
    await channel_layer.group_send(channel, message)
    await channel_layer.close_pools()
```
then call async_to_sync with:
```python
async_to_sync(closing_send)(channel_layer, task_id, {'type': 'update_task_progress', 'data': data})
```

**Comment by czue** [comment]
Thanks for the report/fix! Will give it a couple days for other folks to review but then merge/push up a new version.

**Comment by czue** [comment]
https://github.com/czue/celery-progress/releases/tag/0.2
