### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by mcrot** [czue/celery-progress#11]
In the quickstart example in the documentation, the javascript code is (here for JQuery):
```javascript
// JQuery
var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
$(function () {
  CeleryProgressBar.initProgressBar(progressUrl)
});
```
I wanted to have multiple progress bars and used this in a Django template in a loop and it took me some time to recognize that this does not work: The variable `progressUrl` will be overwritten in each loop iteration and at the end there is only one URL and many progress bars referring to it. 

My suggestion: Move the variable `progressUrl` into the function which is called when the document is ready:
```javascript
// JQuery
$(function () {
  var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
  CeleryProgressBar.initProgressBar(progressUrl);
});
```
In my use case this difference is important.

I could prepare a PR and also fix the missing return from #10. Are you fine with this, @czue ?

**Comment by czue** [comment]
Yes, that would be fantastic, thanks! 

Also you just made me realize that my notification settings were broken for this repo and I missed all the issues :man_facepalming: 

Will go through them asap.
