### ISSUE TITLE
Update two bars relatively to two workers

### ISSUE THREAD

**Issue by NicoCaldo** [czue/celery-progress#114]
So I have two celery workers IDs sent to my frontend and rendered with

```
<div class="progress-wrapper-{{ forloop.counter0 }}">
      <div
        id="progress-bar-{{ forloop.counter0 }}"
        class="progress-bar-{{ forloop.counter0 }} progress-bar-striped"
      >
        &nbsp;
      </div>
    </div>
    <div id="progress-bar-message-{{ forloop.counter0 }}">
      Waiting for progress to start...
    </div>
```

And the JS
```

// vanilla JS version
  document.addEventListener("DOMContentLoaded", function () {
    const task_url = [{% for task_id in celery_ID %}"{% url 'celery_progress:task_status' task_id %}",{% endfor %}]

    for (var i = 0; i<task_url.lenght;i++){
      CeleryProgressBar.initProgressBar(task_url[i], {
        progressBarId: 'progress-bar-' + i,
        progressBarMessageId: 'progress-bar-message-' + i,
      });
    }
  });
```

But in the front end it stays stuck at ` Waiting for progress to start...`

With the analyze tool I can see the indexes are correctly set as well as the URLs but it seems it won't be correctly initialized. Hard coding just the first element (so index 0) I got the error `progressBarElement` in the `celery_progress.js`

What I'm doing wrong? Also, if I want to add an onProgress function (the same for every bar but that updates accordingly to the worker)?

**Comment by czue** [comment]
Without seeing more details it's a bit hard to say what's going on. A few questions that might help point you in the right direction in terms of debugging:

1. Are you seeing any JavaScript errors in the console?
2. In the network tab are the URLs getting polled?
3. If you go to the URLs do you see progress details in JSON?

**Comment by NicoCaldo** [comment]
1. nope
2. nope
3. yes

**Comment by czue** [comment]
That's very strange. Are you sure the initialization code is even getting called? At a minimum the URLs should be polled at least once if you are calling `initProgressBar`

**Comment by NicoCaldo** [comment]
So what' I'm seeing is that if I hard code it, everything works fine
```
// vanilla JS version
  document.addEventListener("DOMContentLoaded", function () {
    const task_url = [{% for task_id in celery_ID %}"{% url 'celery_progress:task_status' task_id %}",{% endfor %}]

      CeleryProgressBar.initProgressBar(task_url[], {
        progressBarId: 'progress-bar-0',
        progressBarMessageId: 'progress-bar-message-0',
      });
  });
```

If I use the for loop

```
// vanilla JS version
  document.addEventListener("DOMContentLoaded", function () {
    const task_url = [{% for task_id in celery_ID %}"{% url 'celery_progress:task_status' task_id %}",{% endfor %}]

    for (var i = 0; i<task_url.lenght;i++){
      CeleryProgressBar.initProgressBar(task_url[i], {
        progressBarId: 'progress-bar-' + String(i),
        progressBarMessageId: 'progress-bar-message-' + String(i),
      });
    }
  });
```

It stops working

**Comment by czue** [comment]
is `task_url.lenght` a typo in your code?

**Comment by NicoCaldo** [comment]
I'm the dumbest programmer out there and VS Code don't even point at the typo...

All good, everything works as intended; thanks

**Comment by czue** [comment]
Glad you got it working!
