### ISSUE TITLE
Progress Bar not syncing with uwsgi+nginx deployment!!

### ISSUE THREAD

**Issue by sindhujit** [czue/celery-progress#15]
It seems that this modules does not properly sync in a production-like deployment of django with uwsgi+nginx. It works fine in our test env. of our automation tool running the django webserver, but in production where we have uwsgi+nginx, it doesn't show the progress.
It gets stuck at "Waiting for progress to start.."

**Comment by czue** [comment]
That's strange I've never had any issues with production deployments. Are you getting any errors in the celery, django, or JS logs/console? Is the task actually running?

**Comment by sindhujit** [comment]
The celery task gets executed fine and I see it getting completed and the response returned as well. However, the task-id URL is not called continuously and the progress bar does not get updated while the task is executing. I have read online it seems it is an nginx issue where it is not able to get the continuous queries about progress from the front-end. Some people have also suggested installing nginx upload progress module, but not sure if going in a different direction is needed at this point.

**Comment by czue** [comment]
The library just uses polling to get the status, so it should not be dependent on the web server unless something strange like throttling is happening.

In the browser are you seeing the requests to the progress status URL getting made? And can you confirm there aren't any javascript errors on the page/

**Comment by sindhujit** [comment]
![Capture](https://user-images.githubusercontent.com/7021803/65479906-32076a80-de44-11e9-8832-97b04bdf7715.PNG)
It seems I am getting an error where it cannot locate /celery-progress. I think apart from defining in urls, it should be defined in my nginx.conf file as well inside the location attribute.

**Comment by czue** [comment]
Yeah, I would guess that it's related to how you're serving staticfiles. I would review these docs and make sure you have a setup that is working: https://docs.djangoproject.com/en/2.2/howto/static-files/deployment/

**Comment by czue** [comment]
oh wait, sorry I misread the error, ignore the staticfiles thing. 

I'm not sure how your setup is working but agreed that either nginx can't find the URL path or django can't find the task (it could be either one).

**Comment by sindhujit** [comment]
You were right. I forgot the way STATIC files are deployed in our E2 and E3 envs are a bit different :)

**Comment by czue** [comment]
great!

**Comment by fauzanebd** [comment]
i have same issue while deploying my flask project on ec2. how do you solve this?

**Comment by czue** [comment]
Could you check these steps? https://github.com/czue/celery-progress/issues/15#issuecomment-534376260

**Comment by sindhujit1** [comment]
Again I am facing the same issue. But now I cannot remember the fix. I don't think its a STATIC folder issue as I did not change anything related to that .

**Comment by sindhujit1** [comment]
![image](https://github.com/czue/celery-progress/assets/60683901/2849c02b-1e77-4c19-9174-a6568679b76f)

**Comment by czue** [comment]
hmm, i would check server logs for that URL and see why it's 404ing.

**Comment by sindhujit1** [comment]
These are the logs from nginx access logs:

`10.5.64.7 - - [11/Mar/2024:22:50:01 -0700] "GET /celery_progress/9134313c-4c9d-4fde-872e-27bb33a4577a/ HTTP/1.1" 404 555 "https://netadc-qa.aexp.com/netadc3/networkinventory/views/datacenternetworkinventory/oobSubnet/LAB/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "x.x.x.x"`

These are the logs from nginx error logs:

`2024/03/12 08:47:40 [error] 2399570#0: *12726 "/usr/share/nginx/html/celery_progress/5d2ba276-3e74-47ad-960f-b9177a497d06/index.html" is not found (2: No such file or directory), client: x.x.x.x, server: x.x.x.x, request: "GET /celery_progress/5d2ba276-3e74-47ad-960f-b9177a497d06/ HTTP/1.1", host: "netadc-qa.aexp.com", referrer: "https://netadc-qa.aexp.com/netadc3/networkinventory/views/datacenternetworkinventory/oobSubnet/LAB/"`

Theres no issues in our E1. But in E2 we use uwsgi+nginx and the job gets stuck at "Waiting for progress to start..". I fixed this before, but from yesterday this issue started happening again. Not sure what I am doing wrong. The static directory seems to be fine as all my other static files are loading properly.

**Comment by czue** [comment]
it doesn't seem like a static files issue. it seems like the `/celery_progress/9134313c-4c9d-4fde-872e-27bb33a4577a/` is 404ing. could be because the url configuration is wrong, task doesn't exist, or the web app and celery app are using different backends. maybe other reasons
