### ISSUE TITLE
import error for deprecated import_by_path

### ISSUE THREAD

**Issue by lyons-heidi** [czue/celery-progress#2]
```
from django.utils.module_loading import import_by_path
ImportError: cannot import name 'import_by_path'
```

Is there a workaround for this yet? import_by_path was deprecated in django 1.9
I'm using django 2.0.6

**Comment by chengweb** [comment]
if your PC is windows platform,  install celery==3.1.25

**Comment by czue** [comment]
Yeah I think this is a `celery` / `django` version incompatibility, not anything to do with this library.
