### ISSUE TITLE
syntax error js file 

### ISSUE THREAD

**Issue by dimkoug** [czue/celery-progress#26]
i get the following error 

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

when i use the default code from the readme

**Comment by czue** [comment]
Whoops, sorry about that @dimkoug . Which code snippet from the README are you referring to specifically?

**Comment by dimkoug** [comment]
In the browser i get that error in console , i think from the javascript file

**Comment by czue** [comment]
I meant what code snippet in the readme?

My best guess is that your ajax request is not returning JSON. Which might indicate you haven't set things up properly and it's returning, e.g. a django error page.

**Comment by dimkoug** [comment]
ok , i'ii check my code for json response , i copied all the code from the readme.

**Comment by czue** [comment]
@dimkoug any update on this? ok if I close it?
