### ISSUE TITLE
Support `result` argument when the task errors

### ISSUE THREAD

**Issue by Nebuchadrezzar** [czue/celery-progress#28]
This is usage question. I'm unclear how to handle errors that I need to show in the progress bar. 

If I raise an error for a celery task, then the celery-progress view's "result" field is null. If a handle an error in a celery task and return the error string, then the celery-progress view rightly populates its "result" field with the returned error, but obviously this is a "false" success. This leaves me wondering how I should correctly pass celery task errors back to the progress bar in a customized onError function?

**Comment by czue** [comment]
So if I'm understanding you correctly I think the answer is that this isn't currently supported. I believe that `result` support was added without thinking about the error use case. Would be great to get some support for implementing this though!

I haven't looked too closely into how it would work, but it seems like you might be able to do something [like this](https://stackoverflow.com/a/24446856/8207)

**Comment by czue** [comment]
@Nebuchadrezzar updated the ticket with what I think the request is - let me know if I have it right!

**Comment by Nebuchadrezzar** [comment]
Yes, that's right, and yes that's better wording.

**Comment by Nebuchadrezzar** [comment]
I believe issue #31 addressed this request.

**Comment by czue** [comment]
Great, thanks!
