### ISSUE TITLE
Getting stuck on the .delay function, webpage never renders

### ISSUE THREAD

**Issue by shadowstriker15** [czue/celery-progress#29]
I have followed the README to include all the original suggested code to try and get a progress bar to display. However, by using the print-technique I notice that my view function can never render the intended HTML file because it gets stuck on the mytask.delay(10) call. Do you know why this would be happening? Is there anything else not included in the README that needs to be added to the code? Additionally, this is my first time ever using an asynchronous task. Thanks!

**Comment by czue** [comment]
Do you have celery setup and running? You'd need to follow something like this: https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by shadowstriker15** [comment]
Nope, I was under the false assumption that this was stand-alone and celery wasn't needed. My bad, thanks for the quick help!

**Comment by formacube** [comment]
Could you add in the documentation as prerequisite that celery needs to be installed ?
there is no mention in the prerequite section:
![image](https://user-images.githubusercontent.com/50452683/82543354-b33e0b00-9b53-11ea-8663-0e9e9a41011b.png)

**Comment by czue** [comment]
Good suggestion! https://github.com/czue/celery-progress/commit/926caa721aaff3958b01a1723ac30eded8a47fb1
