### ISSUE TITLE
celery-progress initialized with 0 of 100 processed..

### ISSUE THREAD

**Issue by Kabir1506** [czue/celery-progress#34]
Hi @czue ,
Although the celery progress-bar works fine for me. I am setting set_progress(start,end). End is not 100.
Even though before tracing the progress the UI shows 0 of 100 processed until the progress starts in backend. Once the process starts in backend it changes to my desired value.

**Comment by eeintech** [comment]
Same problem here, the progress bar initialization message seems to be incorrect.

**Comment by czue** [comment]
thanks, I've also confirmed this is an issue. Feel free to submit a PR! Else I'll add this to the backlog and aim to get it in the next release.

**Comment by eeintech** [comment]
@Kabir1506 A workout I found is to overwrite the `onProgress` function with your own default description (`Starting my task` in the below example):
```
function processProgress(progressBarElement, progressBarMessageElement, progress) {
			progressBarElement.style.width = progress.percent + "%";
			var description = progress.description || "Starting my task";
			progressBarMessageElement.innerHTML = description;
		}

// Progress Bar (JQuery)
	$(function () {
		var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
		CeleryProgressBar.initProgressBar(progressUrl, {
			onProgress: processProgress,
		})
	});
```
