### ISSUE TITLE
Progress bar going from None to Success

### ISSUE THREAD

**Issue by Jean-abb** [czue/celery-progress#39]
Hi @czue , 

Everything seems to doing well but for an unknown reason, i can't see my progress bar evolve in the same time has the info from the task_id url.

I see the progress bar going directly to "success". Looks that the Fetch function return only when the task has finished.

I have followed all the steps from the README

Any known reason ?

Thanks !

**Comment by eeintech** [comment]
@Jean-abb What is your Celery worker output?

**Comment by Jean-abb** [comment]
[2020-07-07 15:53:34,488: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f571e94fc80> (args:('tools.tasks.reverse_dns_resolver', 'b7530b21-9cdd-462b-8e42-b50a3f60718b', {'lang': 'py', 'task': 'tools.tasks.reverse_dns_resolver', 'id': 'b7530b21-9cdd-462b-8e42-b50a3f60718b', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'b7530b21-9cdd-462b-8e42-b50a3f60718b', 'parent_id': None, 'argsrepr': "(['a.a.a.a', 'b.b.b.b', 'c.c.c.c'],)", 'kwargsrepr': "{'full_suffix': True}", 'origin': 'gen22@4f3731b83283', 'reply_to': '24e34057-8253-332d-83fa-19520cb08ff8', 'correlation_id': 'b7530b21-9cdd-462b-8e42-b50a3f60718b', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': False}}, '[[["a.a.a.a", "b.b.b.b", "c.c.c.c"]], {"full_suffix": true}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2020-07-07 15:53:35,018: DEBUG/MainProcess] Task accepted: tools.tasks.reverse_dns_resolver[b7530b21-9cdd-462b-8e42-b50a3f60718b] pid:810
[2020-07-07 15:53:35,059: INFO/PoolWorker-1] Task tools.tasks.reverse_dns_resolver[b7530b21-9cdd-462b-8e42-b50a3f60718b] succeeded in 0.043287962675094604s

And this is whats i have from celer-progress/task_id url: 

{"complete": true, "success": true, "progress": {"current": 100, "total": 100, "percent": 100}, "result": "c.c.c.c;NONE\nb.b.b.b;NONE\na.a.a.a;NONE\n"}

Thanks !

**Comment by Jean-abb** [comment]
In addition :100: 
During long process i can see the progress in real time from the task url. but no progress in parallel bar in the template.

Once progression reach 100%, the progress bar appear in green with success.

**Comment by eeintech** [comment]
@Jean-abb It looks like the Celery task execution time is very short (0.04s).  
Can you please post the code of you Celery task?

**Comment by Jean-abb** [comment]
@eeintech it's same with long task :) here is my task code : 

@shared_task(bind=True)
def reverse_dns_resolver(self, ip_list, full_suffix=False):
    progress_recorder = ProgressRecorder(self)
    ipresolved = ''
    total = len(ip_list)
    if full_suffix:
        for i, ip in enumerate(ip_list):
            ipresolved = f"{ip};{get_dns_record_full_suffix(ip)}\n" + ipresolved
            progress_recorder.set_progress(i, total)
        return ipresolved

**Comment by Jean-abb** [comment]
I have made some test with the "celery_progress.js" script, it seems that the following statement don't work with me :

                if (!data.complete) {
                    setTimeout(updateProgress, pollInterval, progressUrl, options);

With my poor javascript experience, i think this is the part of code which make progressing the bar.
here is an exemple of progress from url with long process : 

{"complete": false, "success": null, "progress": {"current": 805, "total": 1944, "percent": 41.41, "description": "On 804/1944"}}

**Comment by eeintech** [comment]
@Jean-abb Your ```for i, ip in enumerate(ip_list):``` loop is too fast for the progress bar to display on each run, the front-end does not update that fast (can't remember exactly but it in the hundreds of ms). If you want to display progress, try to add a delay on each run:
```
import time # Put at the top of your tasks.py file

for i, ip in enumerate(ip_list):
    ipresolved = f"{ip};{get_dns_record_full_suffix(ip)}\n" + ipresolved
    progress_recorder.set_progress(i, total)
    time.sleep(0.5)
```

**Comment by Jean-abb** [comment]
@eeintech Thank you for your help, i will try it tomorrow and keep you informed !

**Comment by Jean-abb** [comment]
@eeintech unfortunately i have tried with time.sleep(0.5) and time.sleep(1) and i still don't have the progression :/

**Comment by Jean-abb** [comment]
i have added "console.log(data)" on 3 differents states in "celery_progress.js": 

1.  if (data.progress)  = ( index):420 from the console log 
2. if (!data.complete) = Nothing from console log
3. if (data.success) = ( index):429 from the console log 

Here is the result from Chrome console : 

SSO extension (http://192.64.10.230:8081/dns/)
common.js:38 page loaded
common.js:38 starting
common.js:38 no window definitions match http://x.x.x.x:8081/dns/
(index):420 {complete: true, success: true, progress: {…}, result: "...."}
(index):429 {complete: true, success: true, progress: {…}, result: "...."}
(index):417 Fetch finished loading: GET "http://x.x.x.x:8081/celery-progress/3ce4ac4a-c370-4631-9f7e-6a5deeb83778/".
updateProgress @ (index):417
(anonymous) @ (index):456


i have the Fetch result only at the end of the treatment

**Comment by eeintech** [comment]
@Jean-abb How long did the Celery task take to execute with the `time.sleep`? I can't speak for the JS code but were you able to successfully display the timer task progress shown in https://github.com/czue/celery-progress#recording-progress?

**Comment by Jean-abb** [comment]
@eeintech sorry wasting your time :/

It was due to my views.py, i have added a context argument which permit to have a rendering of the result to the frontend at the end of the process.

The fetch function was waiting for this final result before showing anything it's why it was always in "success".

Now it's better :)

**Comment by eeintech** [comment]
@Jean-abb No problem, glad you were able to sort this out!
