### ISSUE TITLE
Task exceptions appear in multiple places on frontend

### ISSUE THREAD

**Issue by EJH2** [czue/celery-progress#44]
As a result of [this change](https://github.com/czue/celery-progress/commit/e69fea4cf95d001e701c0dff46e441727de320aa#diff-1af8afa5271d46d4553e497b42c31f47R15) in #31, an exception triggered in a task will appear in both the result and progress bar message elements using the default configuration. Running a task with the code
```python
@shared_task(bind=True)
def http_error_task(self, number):
    progress_recorder = ProgressRecorder(self)
    for i in range(number):
        time.sleep(.1)
        progress_recorder.set_progress(i+1, number)
        if i == int(number/2):
            raise StopIteration('We broke it!')
    return random()*1000
```
produces a progress bar as shown. ![image](https://user-images.githubusercontent.com/14126443/91368032-04eed500-e7d6-11ea-8d90-d7fff95a875f.png)
It seems counter-intuitive to me to include the exception message in two places, especially since the result makes more sense in the result element than the progress bar area. That's my personal take on it, however. I'd be happy to hear your thoughts on this.

**Comment by czue** [comment]
Agree this is weird behavior. I'll look into it when testing and before the next release. Thanks!

**Comment by czue** [comment]
added logic to only append if resultElement is empty in https://github.com/czue/celery-progress/pull/45

**Comment by czue** [comment]
@EJH2 can you close this once you confirm it's resolved in `0.11`?

**Comment by EJH2** [comment]
This issue has been fixed for HTTP in 0.12, but it seems the change did not carry over to the websocket version.

**Comment by czue** [comment]
Oops sorry! I don't actually have a websocket env.

**Comment by EJH2** [comment]
I created [this project](https://github.com/EJH2/cp_ws-example) a couple of months ago to test previous changes, but it still holds up well enough today as a development playground.

**Comment by OmarWKH** [comment]
To reduce inconsistency between http and websocket they could have more code in common.
The data code ([http](https://github.com/czue/celery-progress/blob/59aa856ba28d847a65a203876b24aca8dd46b0ff/celery_progress/static/celery_progress/celery_progress.js#L77), [ws](https://github.com/czue/celery-progress/blob/59aa856ba28d847a65a203876b24aca8dd46b0ff/celery_progress/static/celery_progress/websockets.js#L42)) can be a common function. The function could return `data.complete` so the http client stops polling and the ws client closes the socket.

Better yet. Make CeleryProgressBar a class and CeleryWebSocketProgressBar a subclass that only overrides the connection code. If that sounds good, I have a branch for this and I can make a PR. Although I didn't test it yet.

**Comment by EJH2** [comment]
That would make sense, as the Python backend for the websocket is a subclass of the http backend. If you could check this out, I would be unopposed to approving it!

**Comment by OmarWKH** [comment]
> That would make sense, as the Python backend for the websocket is a subclass of the http backend. If you could check this out, I would be unopposed to approving it!

done
