### ISSUE TITLE
[Question] Is it possible to display multiple loading bars for multiple tasks queued at the same time?

### ISSUE THREAD

**Issue by P-Sood** [czue/celery-progress#49]
I am not that familiar with celery and don't even know if it can run multiple tasks concurrently, but if it does, would there be a way to support multiple loading bars that show the progress of each task?

**Comment by EJH2** [comment]
The library does support initializing and displaying multiple progress bars, which can be accomplished by wrapping the initialization script in the [README](https://github.com/czue/celery-progress/blob/af964fe912379086861787bd1f45d6edaf55555d/README.md#initialize-the-progress-bar) in a for-loop. Another way would be to wrap the same example in a for-loop, but adding a callback that starts the next bar after the previous one has finished. Both methods would suit your needs, as I use them personally in production. If this is what you're looking for, feel free to close the issue 🙂.

**Comment by Jedrzed** [comment]
hello, i also want to display multiple bars at same time. for example, i have 5 objects in log_list , but when i use for-loop, only can see one bar and five message, what should i do to see five bar?
`{% for log in log_list %}
            <div class='progress-wrapper'>
                <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
            </div>
            <div id="progress-bar-message">Waiting for progress to start...</div>
            
            <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
            
            <script>
                // vanilla JS version
                $(function () {
                    var progressUrl = "{% url 'celery_progress:task_status' log.task_id %}";
                    CeleryProgressBar.initProgressBar(progressUrl)
                });
            </script>
            {% endfor %}`

**Comment by EJH2** [comment]
Here's a simple way that should do what you're trying to accomplish. Hope this helps!
```js
{% for task_id in task_ids %}
<div class='progress-wrapper-{{ forloop.counter0 }}'>
    <div id='progress-bar-{{ forloop.counter0 }}' class='progress-bar-{{ forloop.counter0 }}' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
    <div id="progress-bar-message-{{ forloop.counter0 }}">Waiting for progress to start...</div>
    <div id="progress-result-{{ forloop.counter0 }}"></div>
</div>
{% endfor %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const task_urls = [
            {% for task_id in task_ids %}"{% url 'celery_progress:task_status' task_id %}",
        {% endfor %}];
        for (var i = 0; i < task_urls.length; i++) {
            CeleryProgressBar.initProgressBar(task_urls[i], {
                progressBarId: "progress-bar-" + i,
                progressBarMessageId: "progress-bar-message-" + i,
                resultElementId: "progress-result-" + i
            });
        }
    });
</script>
```

**Comment by NicoCaldo** [comment]
Sorry to re-open the issue but, what about the onProgress function?

**Comment by czue** [comment]
You should be able to pass `onProgress` to `initProgressBar`  for each element and it will work as expected.
