### ISSUE TITLE
Support task retries

### ISSUE THREAD

**Issue by OmarWKH** [czue/celery-progress#53]
Retrying tasks causes an error.

I think it's because Progress.get_info reaches the last line and returns an exception. The view tries to send it as JSON but can't.

https://github.com/czue/celery-progress/blob/af964fe912379086861787bd1f45d6edaf55555d/celery_progress/backend.py#L95

Example task:
```python
def retry_task():
    try:
        raise StopIteration('We broke it!')
    except StopIteration as exc:
        raise self.retry(exc=exc)
```

**Comment by EJH2** [comment]
Fixed in #61
