### ISSUE TITLE
Progress jumping from waiting to success when i use CELERY_RESULT_BACKEND = "django-db"

### ISSUE THREAD

**Issue by capancheta** [czue/celery-progress#55]
this does not happen if i use CELERY_RESULT_BACKEND == redis.
The status of the task while processing appears as so:

{"complete": false, "success": null, "progress": {"pending": true, "current": 0, "total": 100, "percent": 0}}

once completed though, all values are correct:

{"complete": true, "success": true, "progress": {"current": 100, "total": 100, "percent": 100}, "result": {<VALID_RESULTS>}}

Thank you!

**Comment by EJH2** [comment]
Do you have an example task where this occurs? This definitely not the intended behavior, and any help you can give at reproducing this would greatly assist us in fixing this.

**Comment by oguzhancelikarslan** [comment]
I tested it and works like a charm. I used django-db as backend.

**Comment by EJH2** [comment]
Hmm, will definitely need more info from @capancheta when they have the time.

**Comment by capancheta** [comment]
i must have something wrong with my celery config. i'll continue tinkering with it and report back. thank you all!

**Comment by capancheta** [comment]
figured it out, my function has an @transactions.atomic() decorator. doesnt play nice probably because celery-progress requires that the backend MUST be updated(re: data commited) in the first place.

**Comment by EJH2** [comment]
Yeah, the only way to communicate the state between the task and the HTTP view is to pull off of the backend. Glad you were able to solve your issue, though!
