### ISSUE TITLE
views.py - row 8 - json.dumps() cannot serialize Decimal objects

### ISSUE THREAD

**Issue by chauhoang99** [czue/celery-progress#7]
I got this problem on my side. The get_progress views failed all the times because of Decimal object in the result returned by progress.get_info().

In my fork I did this update to handle the error. Would be great if you can review your main version. Thank you for this great package btw, saved tons of time for me :)

![image](https://user-images.githubusercontent.com/40813780/48825271-de4e6f80-eda1-11e8-8e04-ae8aa1ae3261.png)

**Comment by chisvi** [comment]
I've submitted a PR #9  that solves this. Maybe we can get it merged and deploy a new version to Pypi so we can easily deploy projects using celery-progress without needing to modify the code.

**Comment by hscspring** [comment]
i don't think it's good to use.

**Comment by czue** [comment]
fixed in `0.0.4` - thanks!
