### ISSUE TITLE
Problem loading progress bar

### ISSUE THREAD

**Issue by Deguise** [czue/celery-progress#70]
Hello, 
Could you add [never_cache](https://docs.djangoproject.com/en/dev/topics/http/decorators/#django.views.decorators.cache.never_cache) decorator to [get_progress](https://github.com/czue/celery-progress/blob/018f059a29d7ca78cc52ff0bc5c13b649b391770/celery_progress/views.py#L7) view ? This will avoid having bar loading problems when [UpdateCacheMiddleware](https://docs.djangoproject.com/en/dev/ref/middleware/#django.middleware.cache.UpdateCacheMiddleware) is activated.
Thanks, 
Martin.

**Comment by czue** [comment]
this makes a lot of sense to me.
