### ISSUE TITLE
Maintenance and support for Django >= 3.1

### ISSUE THREAD

**Issue by abedyngash** [czue/celery-progress#78]
This piece of warning comes up when using Django 3.1

```
celery_progress/urls.py:6: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r'^(?P<task_id>[\w-]+)/$', views.get_progress, name='task_status')
```
That should be corrected in the next release, I suppose.

**Comment by czue** [comment]
oops - thanks for the heads up! will prioritize this

**Comment by abedyngash** [comment]
> oops - thanks for the heads up! will prioritize this

Actually opened a pull request for the same. Check #79

**Comment by czue** [comment]
Ah great, thanks for the contribution!
