### ISSUE TITLE
NoReverseMatch at /fv/ Reverse for 'task_status' with arguments '('',)' not found. 1 pattern(s) tried: ['celery-progress/(?P<task_id>[\\w-]+)/$']

### ISSUE THREAD

**Issue by jecker7** [czue/celery-progress#8]
Getting the following error when deploying:

NoReverseMatch at /fv/
Reverse for 'task_status' with arguments '('',)' not found. 1 pattern(s) tried: ['celery-progress/(?P<task_id>[\\w-]+)/$']

**Comment by sindhujit** [comment]
I have the same issue. +1

**Comment by snmateen** [comment]
i'm seeing the same issue as well.

```
django.urls.exceptions.NoReverseMatch: Reverse for 'task_status' with arguments '('',)' not found. 1 pattern(s) tried: ['celery-progress/(?P<task_id>[\\w-]+)/$']
```

**Comment by nonnimartin** [comment]
Same issue. Any suggestions?

**Comment by lie-nielsen** [comment]
In settings.py, try this:
path('celery-progress/', include('celery_progress.urls')),

**Comment by czue** [comment]
Oh dear, sorry about the delayed reply.

If the task is called *in the view* and then you are rendering the progress bar on the resulting page then you should just pass `task_id` directly from the view.

See [this section of the readme](https://github.com/czue/celery-progress#displaying-progress) for how that looks.

If you are triggering the task from the page itself (e.g. via ajax or something) it's a bit trickier. One hack you can do is something like the below using a stub task id to get the URL:

```javascript
// on page load
var progressUrl = "{% url 'celery_progress:task_status' 'task-id-stub' %}";
// in callback function - assumes api response returns the task id
var taskUrl = progressUrl.replace('task-id-stub', response.text);
```
Does that help?

**Comment by Acessos-Ad3** [comment]
Hi, czue
I'm with the same issue, i tried your answer but, didn't worked for me,

**Comment by czue** [comment]
Can you share your view code and template?

**Comment by AmineHosni** [comment]
I

**Comment by AmineHosni** [comment]
Same here. My console shows 

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)` at
127.0.0.1:8000/celery-progress/bddc2f0a-91d5-42ca-bf94-a5deb8d55305/ which shows the Django error: 
`'DisabledBackend' object has no attribute '_get_task_meta_for'`

I added these lines, based on the [2nd ](https://stackoverflow.com/questions/23215311/celery-with-rabbitmq-attributeerror-disabledbackend-object-has-no-attribute) solution, right before the task definition
 `from celery import Celery`
`app = Celery('tasks', backend='rpc://', broker='pyamqp://')` 

With this code in the Views, 
```
def pdf_add(request, slug):
                # some code to upload a pdf file and split each page into .pdf and .jpg for further work
                # below work is just a sample example to test the library
		result = obj.my_task.delay(10)
		context['task_id'] = result.task_id
		return redirect('projects_details',project.slug)
	pdf = PDF_file()
	result = pdf.my_task.delay(10)
	context['task_id'] = result.task_id
	return render(request, template_name, context)
```
Doing so, removes the console error as it now has a backend but not the one of celery-progress (I think), I even see my terminal refreshing every second with Get / celery-progress/some_task_id but the "0 of 100 proceeded" doesn't change when the task is called.
I also tried adding this line, based on the 3rd solution on the same previous link:
`CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'` but it didn't change a thing.
I don't know how to make it pick the library's backend.
And if I remove the ```	pdf = PDF_file()
	result = pdf.my_task.delay(10)
	context['task_id'] = result.task_id```
from the GET part of the View function, I'm back to the starting problem with  `NoReverseMatch..." error back`

**Comment by czue** [comment]
celery and your web app (I assume django) need to use the same backend.

So if you're using `rpc://` when you call celery then you should add `CELERY_RESULT_BACKEND='rpc://'` I believe.

**Comment by sindhujit** [comment]
Hi @czue 
I followed the corrections you stated. For me, the no reverse error is fixed. However, the issue now is we are getting the task ID only after the task is completely executed. So the progress does not start until the entire task is completed.

**Comment by czue** [comment]
Are you using `ALWAYS_EAGER`?

**Comment by ludwigwittgenstein2** [comment]
I have the same issue. 
![image](https://user-images.githubusercontent.com/21267065/65641600-d60f2400-dfb2-11e9-82f7-479a5916566e.png)

**Comment by czue** [comment]
@ludwigwittgenstein2 it looks like the task ID is blank, which either means you're not properly passing it to the template, or the celery setup is not returning valid task IDs (check the result backend).

**Comment by czue** [comment]
Closing this out since I believe this is a configuration problem and not an issue with the library.

**Comment by phatberstromgg** [comment]
Hi @czue, I have tried your advice but the error still there. In my case, the webpage was worked but when I upload a video, the web shows me the error. It is said the same look as the post of @ludwigwittgenstein2. Could you help me, please? Hope to hear from you soon. 

Thank you so much.
Best regards.

> Oh dear, sorry about the delayed reply.
> 
> If the task is called _in the view_ and then you are rendering the progress bar on the resulting page then you should just pass `task_id` directly from the view.
> 
> See [this section of the readme](https://github.com/czue/celery-progress#displaying-progress) for how that looks.
> 
> If you are triggering the task from the page itself (e.g. via ajax or something) it's a bit trickier. One hack you can do is something like the below using a stub task id to get the URL:
> 
> ```js
> // on page load
> var progressUrl = "{% url 'celery_progress:task_status' 'task-id-stub' %}";
> // in callback function - assumes api response returns the task id
> var taskUrl = progressUrl.replace('task-id-stub', response.text);
> ```
> 
> Does that help?
