### ISSUE TITLE
Introduce changelog

### ISSUE THREAD

**Issue by hansegucker** [czue/celery-progress#81]
Reviewing changes of this package while updating dependencies is very hard because there is no changelog. It would be great to introduce it to get more transparency.

**Comment by czue** [comment]
Thanks, I think this is a great idea and something we should put in place moving forwards.

**Comment by czue** [comment]
This has been introduced here. All releases prior to 0.1.2 are bundled together, but this will be maintained moving forwards.: https://github.com/czue/celery-progress/releases/
