### ISSUE TITLE
Handling a FileResponse

### ISSUE THREAD

**Issue by kgeographer** [czue/celery-progress#86]
I have a Django function that generates a csv or json file from database queries and returns a FileResponse, which opens a system File/Save dialog on completion. This works ok, except that some requests can take a while (10-30 seconds), so I want Celery to manage this and provide a progress bar. The return looks like this in a `download_file()` function -- after writing a file `fn`:
```
response = FileResponse(open(fn, 'rb'), content_type='text/json')
response['Content-Disposition'] = 'attachment; filename="'+os.path.basename(fn)+'"'
return response
```

I use Celery for other long tasks in the app, so I'm reasonably familiar with it. None of those return files though--they perform some tasks to retrieve data and write it to the database, and return only a JSON object summarizing results.

Using your library, I've made `download_file` a `@task`, initiated it with form submission for parameters, and it generates the file as expected, but Celery errors out with 
`EncodeError: Object of type FileResponse is not JSON serializable`

I saw a suggestion to wrap the file in ContentFile() like so
`response = FileResponse(ContentFile(open(fn, 'rb')), content_type='text/json')`
The file still gets created, but the Celery error is now 
`a bytes-like object is required, not '_io.BufferedReader'`

All this means that I can't get the File/Save dialog to open on completion. After lots of searching, I've found nothing about Celery handling Django FileResponse -- any ideas?

**Comment by czue** [comment]
Offhand, I'm not sure if celery allows passing a result like this. Likely what you will need to do is temporarily store the file somewhere (e.g. in Redis or on the file system), then pass back a *handle* to the file from the task, then add logic in the web tier to retrieve and serve that file via a second request.

Does that make sense?

**Comment by kgeographer** [comment]
Yes, that is certainly the case -- and what you suggest is what I have ended up doing. My Celery task now simply returns some JSON with the name of the file that was written, and in the `success` action of the ajax I stop a spinner, build an href with the filename then click() it. That generates the system File/Save dialog I need. Seems pretty 'klugey' to me but hey, it works. Still some kinks to work out with progress reporting, but now past that big stumbling block. Thanks, and thanks for a useful library. -kg

**Comment by czue** [comment]
No problem and sounds good!
