### ISSUE TITLE
Legacy install method will be deprecated soon

### ISSUE THREAD

**Issue by eeintech** [czue/celery-progress#98]
``` bash
$ pip --version
pip 22.3
$ pip install celery-progress
Collecting celery-progress
  Downloading celery-progress-0.1.2.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: celery-progress
```

>  DEPRECATION: celery-progress is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

```
  Running setup.py install for celery-progress ... done
Successfully installed celery-progress-0.1.2
```

EDIT: Quoted the deprecation warning

**Comment by czue** [comment]
thanks - I'll look into this as soon as i can

**Comment by eeintech** [comment]
Nice, thanks!

**Comment by eeintech** [comment]
By the way @czue your last release says `0.1.2` while PyPI is at `0.1.3`, maybe you want to fix this :smiley:

**Comment by czue** [comment]
eep, thanks https://github.com/czue/celery-progress/releases/tag/0.1.3
